# Generated by Django 3.2 on 2024-09-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universidad__', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='curso',
            name='id_curso',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='id_departamento',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='id_empleado',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='id_estudiante',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='id_profesor',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
