# Generated by Django 3.2 on 2024-09-02 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universidad__', '0003_auto_20240901_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='id_curso',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
